### ISSUE TITLE
How to get original functions of tokenized function codes that are present in 'dataset_saved/classcial_summarization'

### ISSUE THREAD

**Issue by Li-Lixuan** [NougatCA/SPT-Code#2]
Hi, thanks for sharing your great work!

I have downloaded your tokenized data that are present in 'dataset_saved/classcial_summarization'.  But how could I map the tokenized code to the original functions from [https://github.com/EdinburghNLP/code-docstring-corpus](url).

It could be very helpful if you provide some guidelines to get the original function. 

Thanks a lot!

**Comment by NougatCA** [comment]
Hi, 

I'm sorry to reply so late, due to disk space limitations, all my data of this work is on a computer that I don't use very often and I can't get to it at the moment.

As soon as I can get that data, I'll be looking to see if I have what you need, so please excuse me!

Thanks for your interest in our work!
